name: ngopay
description: UI Toolkit for the Ngopay Flutter Application
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  beamer: ^1.5.3
  cupertino_icons: ^1.0.5
  curved_progress_bar: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.5
  freezed_annotation: ^2.1.0
  hooks_riverpod: ^2.0.2
  pubspec_parse: ^1.2.1
  riverpod_annotation: ^1.0.2
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0

dev_dependencies:
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.1
  json_serializable: ^6.3.0
  riverpod_generator: ^1.0.2
  very_good_analysis: ^2.0.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  # generate: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Italic.ttf
          weight: 400
          style: italic

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
